# Generated by Django 5.1.6 on 2025-02-20 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horas', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('jornada', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.curso')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.estudiante')),
            ],
        ),
    ]
